---
instances: []
witnesses:
  - header:
      version: 1.0.0
      field_characteristic:
        - 2
      field_degree: 1
    short_witness:
      - - 1
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 1
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 0
      - - 1
      - - 1
relations: []

